### ISSUE TITLE
Invalid value encountered in divide

### ISSUE THREAD

**Issue by kaarelr** [mikkokotila/sanity#1]
Running the example notebook with default data leads to runtime warning and invalid results.

`/usr/local/lib/python2.7/site-packages/sanity/market_simulator.py:120: RuntimeWarning: invalid value encountered in divide
  players[:, 5] = players[:, 5] / players[:, 4]`

<img width="666" alt="image" src="https://user-images.githubusercontent.com/14364284/61277747-78dd4200-a7bb-11e9-880c-059d7602249a.png">

**Comment by mikkokotila** [comment]
Do you still get it when you're on Python >=3.5?

**Comment by kaarelr** [comment]
Upgraded to Python 3.6.8 and the problem is solved.
